name = "SparseMatrixIdentification"
uuid = "2607229e-3272-44a7-bc4a-cd97a328dfbf"
version = "1.0.0-DEV"
authors = ["Anastasia Dunca"]

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
BandedMatrices = "1.10.2"
ToeplitzMatrices = "0.8.5"
julia = "1.6.7"
[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "BenchmarkTools", "Test"]
